# Use a base image oficial do PostgreSQL
FROM postgres:latest

# Define as variáveis de ambiente para a configuração do PostgreSQL
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydb

# Copia o arquivo models.py para dentro do contêiner
COPY models.py /docker-entrypoint-initdb.d/

# Define um comando de entrada customizado para executar o modelo
# Será executado automaticamente ao criar o contêiner
CMD ["postgres"]
