version: '3.8'

services:
  api:
    image: pablorlv/ponderada4_api:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  model:
    image: pablorlv/ponderada4_db:latest
    depends_on:
      - postgres

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"