version: '3.1'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "5000"
    ports:
      - 5000:5000
    depends_on:
      - db
    container_name: pablorlvapi

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - "5432"
    ports:
      - 5432:5432
    container_name: pablorlvdb